import math

## User variables
# OLLAMA_LLM = "gemma2:2b-instruct-q5_0"

## System variables
SEARCH_DEPTH_CAP = 50
NUMBER_OF_NEW_NODES_PER_EXPANSION = 3
NUMBER_OF_REWARD_SAMPLES = 3
NUMBER_OF_TERMINAL_CHECK_SAMPLES = 3
TERMINAL_SCORE_THRESHOLD = 85
DIMINISHING_RETURNS_THRESHOLD = 0.01
OVERSCORE_REDUCTION_CONSTANT = 5
UCT_E = 0.1
UCT_C = math.sqrt(2)
